apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  creationTimestamp: "2022-02-15T13:20:00Z"
  generation: 1
  name: cold-test-off
  namespace: openshift-mtv
  resourceVersion: "27988172"
  uid: 61dd8c8a-9422-472c-815a-e0ed75ae6cce
spec:
  archived: false
  description: ""
  map:
    network:
      name: cold-test-off-nngbj
      namespace: openshift-mtv
    storage:
      name: cold-test-off-4rjxf
      namespace: openshift-mtv
  provider:
    destination:
      name: host
      namespace: openshift-mtv
    source:
      name: node05
      namespace: openshift-mtv
  targetNamespace: mguetta
  vms:
  - hooks: []
    id: vm-19125
  warm: false
status:
  conditions:
  - category: Required
    lastTransitionTime: "2022-02-15T13:20:00Z"
    message: The migration plan is ready.
    status: "True"
    type: Ready
  - category: Advisory
    durable: true
    lastTransitionTime: "2022-02-15T13:22:42Z"
    message: The plan execution has SUCCEEDED.
    status: "True"
    type: Succeeded
  migration:
    completed: "2022-02-15T13:22:42Z"
    history:
    - conditions:
      - category: Advisory
        durable: true
        lastTransitionTime: "2022-02-15T13:22:42Z"
        message: The plan execution has SUCCEEDED.
        status: "True"
        type: Succeeded
      map:
        network:
          generation: 1
          name: cold-test-off-nngbj
          namespace: openshift-mtv
          uid: a46901dc-ac5b-4639-9707-7e96db2f07fe
        storage:
          generation: 1
          name: cold-test-off-4rjxf
          namespace: openshift-mtv
          uid: 849ada76-8202-4f4a-af32-d53a8744c2a7
      migration:
        generation: 1
        name: cold-test-off-1644931203469
        namespace: openshift-mtv
        uid: 3db35678-933a-4863-a031-64b0bd945048
      plan:
        generation: 1
        name: cold-test-off
        namespace: openshift-mtv
        uid: 61dd8c8a-9422-472c-815a-e0ed75ae6cce
      provider:
        destination:
          generation: 1
          name: host
          namespace: openshift-mtv
          uid: 0bde99b7-c8bb-4b7c-b1d3-aa567a314c6b
        source:
          generation: 1
          name: node05
          namespace: openshift-mtv
          uid: 2fe3af5b-1e17-4e28-a681-8a847ccc165c
    started: "2022-02-15T13:20:04Z"
    vms:
    - completed: "2022-02-15T13:22:42Z"
      conditions:
      - category: Advisory
        durable: true
        lastTransitionTime: "2022-02-15T13:22:42Z"
        message: The VM migration has SUCCEEDED.
        status: "True"
        type: Succeeded
      id: vm-19125
      name: mtv-rhel8-sanity
      phase: Completed
      pipeline:
      - completed: "2022-02-15T13:20:35Z"
        description: Initialize migration.
        name: Initialize
        progress:
          completed: 1
          total: 1
        started: "2022-02-15T13:20:04Z"
      - annotations:
          unit: MB
        completed: "2022-02-15T13:21:11Z"
        description: Transfer disks.
        name: DiskTransfer
        phase: Completed
        progress:
          completed: 12288
          total: 12288
        started: "2022-02-15T13:20:42Z"
        tasks:
        - annotations:
            unit: MB
          completed: "2022-02-15T13:21:11Z"
          name: '[rhv-v2v-performance-testing] mtv-rhel8-sanity/mtv-rhel8-sanity.vmdk'
          phase: Completed
          progress:
            completed: 12288
            total: 12288
          reason: Transfer completed.
          started: "2022-02-15T13:20:42Z"
      - completed: "2022-02-15T13:22:42Z"
        description: Convert image to kubevirt.
        name: ImageConversion
        progress:
          completed: 1
          total: 1
        started: "2022-02-15T13:21:18Z"
      restorePowerState: "Off"
      started: "2022-02-15T13:20:04Z"
  observedGeneration: 1
