apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.pod.retainAfterCompletion: "true"
    cdi.kubevirt.io/storage.pod.vddk.version: 7.0.2
  creationTimestamp: "2022-02-15T13:20:20Z"
  generateName: cold-test-off-vm-19125-
  generation: 28
  labels:
    migration: 3db35678-933a-4863-a031-64b0bd945048
    plan: 61dd8c8a-9422-472c-815a-e0ed75ae6cce
    vmID: vm-19125
  name: cold-test-off-vm-19125-qrzsv
  namespace: mguetta
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: false
    kind: VirtualMachine
    name: mtv-rhel8-sanity
    uid: 9c0cf6c1-4173-4ac9-91c0-449039a7b831
  resourceVersion: "27986552"
  uid: 61732ccb-0851-4387-a564-0ee54a9af318
spec:
  source:
    vddk:
      backingFile: '[rhv-v2v-performance-testing] mtv-rhel8-sanity/mtv-rhel8-sanity.vmdk'
      initImageURL: cnv-qe-server.rhevdev.lab.eng.rdu2.redhat.com:5000/vddk-images/vddk:v702
      secretRef: cold-test-off-vm-19125-4tzbc
      thumbprint: 31:14:EB:9E:F1:78:68:10:A5:78:D1:A7:DF:BB:54:B7:1B:91:9F:30
      url: https://rhev-node-05.rdu2.scalelab.redhat.com/sdk
      uuid: 420353df-9d7e-7eed-1dc1-7a327155b442
  storage:
    resources:
      requests:
        storage: 12Gi
    storageClassName: nfs
status:
  claimName: cold-test-off-vm-19125-qrzsv
  conditions:
  - lastHeartbeatTime: "2022-02-15T13:20:20Z"
    lastTransitionTime: "2022-02-15T13:20:20Z"
    message: PVC cold-test-off-vm-19125-qrzsv Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2022-02-15T13:21:04Z"
    lastTransitionTime: "2022-02-15T13:21:04Z"
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2022-02-15T13:21:04Z"
    lastTransitionTime: "2022-02-15T13:21:04Z"
    message: 'Import Complete; VDDK: {"Version":"7.0.2","Host":""}'
    reason: Completed
    status: "False"
    type: Running
  phase: Succeeded
  progress: 100.0%
