apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubemacpool.io/transaction-timestamp: "2022-02-15T13:20:27.740683479Z"
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2022-02-15T13:20:27Z"
  generation: 1
  labels:
    migration: 3db35678-933a-4863-a031-64b0bd945048
    plan: 61dd8c8a-9422-472c-815a-e0ed75ae6cce
    vmID: vm-19125
  name: mtv-rhel8-sanity
  namespace: mguetta
  resourceVersion: "27985894"
  uid: 9c0cf6c1-4173-4ac9-91c0-449039a7b831
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        clock:
          timer: {}
          timezone: UTC
        cpu:
          cores: 1
          sockets: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: vol-0
          inputs:
          - bus: virtio
            name: tablet
            type: tablet
          interfaces:
          - macAddress: 00:50:56:83:f7:d0
            masquerade: {}
            model: virtio
            name: net-0
        features:
          acpi: {}
        firmware:
          bootloader:
            bios: {}
          serial: 420353df-9d7e-7eed-1dc1-7a327155b442
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: net-0
        pod: {}
      volumes:
      - dataVolume:
          name: cold-test-off-vm-19125-qrzsv
        name: vol-0
status:
  conditions:
  - lastProbeTime: "2022-02-15T13:20:27Z"
    lastTransitionTime: "2022-02-15T13:20:27Z"
    message: VMI does not exist
    reason: VMINotExists
    status: "False"
    type: Ready
  printableStatus: Provisioning
  volumeSnapshotStatuses:
  - enabled: false
    name: vol-0
    reason: 'No VolumeSnapshotClass: Volume snapshots are not configured for this
      StorageClass [nfs] [vol-0]'
